service: MedscribeApp
frameworkVersion: '2'

provider:
  name: aws
  region: us-west-1
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: medscribe-paitent-intake
      localDir: ../client/build

resources:
  Resources:
    MedscribeAppBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: medscribe-paitent-intake
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    S3AccessPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: MedscribeAppBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::medscribe-paitent-intake/*
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: medscribe-paitent-intake.s3.amazonaws.com
              Id: MedscribeApp
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
          Enabled: 'true'
          DefaultRootObject: index.html
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - POST
              - PUT
              - PATCH
            TargetOriginId: MedscribeApp
            ForwardedValues:
              QueryString: 'false'
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
          ViewerCertificate:
            CloudFrontDefaultCertificate: true
